# Generated by Django 5.1.6 on 2025-05-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shifts', '0002_shift_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_optimized',
            field=models.BooleanField(default=False, help_text='Флаг, указывающий, что смена была создана автоматически через оптимизацию'),
        ),
    ]
