# Generated by Django 5.1.6 on 2025-05-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='min_basic_workers',
            field=models.PositiveIntegerField(default=0, help_text='Minimum number of basic workers required in the warehouse'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='min_drivers',
            field=models.PositiveIntegerField(default=0, help_text='Minimum number of cargo drivers required in the warehouse'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='min_engineers',
            field=models.PositiveIntegerField(default=0, help_text='Minimum number of engineers required in the warehouse'),
        ),
    ]
