# Generated by Django 5.1.6 on 2025-03-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin_requested',
            field=models.BooleanField(default=False, help_text='Designates whether the user has requested an admin role.'),
        ),
    ]
