# Generated by Django 5.1.6 on 2025-05-02 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_is_staff'),
        ('warehouses', '0002_warehouse_min_basic_workers_warehouse_min_drivers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerWarehousePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=1, help_text='Priority level (1 is highest)')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, help_text="Distance in km from worker's location to the warehouse", max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_preferences', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_preferences', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['priority'],
                'unique_together': {('user', 'warehouse')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_warehouses',
            field=models.ManyToManyField(blank=True, related_name='preferred_by_workers', through='user.WorkerWarehousePreference', to='warehouses.warehouse'),
        ),
        migrations.CreateModel(
            name='WorkerQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_type', models.CharField(choices=[('basic_worker', 'Basic Worker'), ('cargo_driver', 'Cargo Driver'), ('engineer', 'Engineer')], max_length=20)),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='Skill level from 1 to 5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'qualification_type')},
            },
        ),
    ]
