# Generated by Django 5.1.6 on 2025-05-02 17:26

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0002_warehouse_min_basic_workers_warehouse_min_drivers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('forecasted_volume', models.PositiveIntegerField(default=0, help_text='Forecasted total cargo volume in cubic meters', validators=[django.core.validators.MinValueValidator(0)])),
                ('forecasted_weight', models.PositiveIntegerField(default=0, help_text='Forecasted total cargo weight in kg', validators=[django.core.validators.MinValueValidator(0)])),
                ('forecasted_packages', models.PositiveIntegerField(default=0, help_text='Forecasted total package count', validators=[django.core.validators.MinValueValidator(0)])),
                ('forecasted_basic_workers', models.PositiveIntegerField(default=0, help_text='Forecasted number of basic workers needed')),
                ('forecasted_drivers', models.PositiveIntegerField(default=0, help_text='Forecasted number of drivers needed')),
                ('forecasted_engineers', models.PositiveIntegerField(default=0, help_text='Forecasted number of engineers needed')),
                ('confidence_level', models.DecimalField(decimal_places=2, default=0, help_text='Confidence level of the forecast (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_forecasts', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('warehouse', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CargoLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateField()),
                ('incoming_volume', models.PositiveIntegerField(default=0, help_text='Incoming cargo volume in cubic meters', validators=[django.core.validators.MinValueValidator(0)])),
                ('outgoing_volume', models.PositiveIntegerField(default=0, help_text='Outgoing cargo volume in cubic meters', validators=[django.core.validators.MinValueValidator(0)])),
                ('incoming_weight', models.PositiveIntegerField(default=0, help_text='Incoming cargo weight in kg', validators=[django.core.validators.MinValueValidator(0)])),
                ('outgoing_weight', models.PositiveIntegerField(default=0, help_text='Outgoing cargo weight in kg', validators=[django.core.validators.MinValueValidator(0)])),
                ('incoming_packages', models.PositiveIntegerField(default=0, help_text='Number of incoming packages', validators=[django.core.validators.MinValueValidator(0)])),
                ('outgoing_packages', models.PositiveIntegerField(default=0, help_text='Number of outgoing packages', validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_basic_workers', models.PositiveIntegerField(default=0, help_text='Estimated number of basic workers needed for this load')),
                ('estimated_drivers', models.PositiveIntegerField(default=0, help_text='Estimated number of drivers needed for this load')),
                ('estimated_engineers', models.PositiveIntegerField(default=0, help_text='Estimated number of engineers needed for this load')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_loads', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('warehouse', 'date')},
            },
        ),
    ]
