# Generated by Django 5.1.6 on 2025-05-02 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargoload',
            name='incoming_packages',
        ),
        migrations.RemoveField(
            model_name='cargoload',
            name='incoming_volume',
        ),
        migrations.RemoveField(
            model_name='cargoload',
            name='outgoing_packages',
        ),
        migrations.RemoveField(
            model_name='cargoload',
            name='outgoing_volume',
        ),
    ]
