# Generated by Django 5.1.6 on 2025-05-02 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_remove_cargoload_incoming_packages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargoforecast',
            name='forecasted_packages',
        ),
        migrations.RemoveField(
            model_name='cargoforecast',
            name='forecasted_volume',
        ),
        migrations.RemoveField(
            model_name='cargoload',
            name='incoming_weight',
        ),
        migrations.RemoveField(
            model_name='cargoload',
            name='outgoing_weight',
        ),
        migrations.AddField(
            model_name='cargoload',
            name='total_weight',
            field=models.PositiveIntegerField(default=0, help_text='Total cargo weight in kg', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
